language: node_js
node_js:
  - 5.7.0
sudo: required
services:
  - docker
before_install:
  - docker-compose -f docker-compose-test build
  - docker-compose -f docker-compose-test up
script:
  - npm test
deploy:
  provider: heroku
  app: api-gateway-staging
  api_key:
    secure: cqtB4Bn20067ege6X03Q/AiKdeyIp9TF+ujm6nV4dtYVWzWrBlhNjAqixrbf7FwNAC518Jy55mtVo7E98eaoxmIuZibi9shKj0/EkYJOrFDnH0Gu2o4fCgy87Tr7v3XukPJkcznDmgMOWXKM+rqSD0/zPfSOctbRlyfcUvP9g5qC8PPQDhO71HKDaWwl1U73cEqdR9kkn92B7XzXeyI2li3Gde+3twlsPot5eDI01S6mrFY+hSSDqlD7hg1HpPhBnmAIeMOkgtTjz1d3F51ZDufiWZ8U6tegjjeTOThyiN5Ad5UkZNh2r+xXrDK4SYiUGJK+CuQyNhkjX+mTBIOGys7OLIpAzOY6cv21dW0kTZsv58BVc4DV6S8PMJKlyMh35aicOPk5Ji+tW15B3YOZ/Bf22nx8kOV0aIa9NVZjam+U1bpvZp8HMUeGVkLotKXgrhCY7E4ZzzTt3DHK11x2WRNWMfkmrWXmht9EniW26jFmYq+U0QVRFZ+a8Xh/KHNdY+abFB5TaSp2POJx6gU2yIPf1/XexGlgXWPht0zJwX+VkRx8y/iuX5+m0erKyxLI07vjU0o27jKVHa/oW2mowu3k5Wd0+Lc6BxgJ/U6tKVHtvh6I2BFHHUNOTK+8kUEKkirzgDrQbouEw4e/T6W/UMqzULv8ABXJ9wX5NUiISPk=
