language: node_js
node_js:
- 5.7.0
sudo: required
services:
- docker
script:
- docker-compose -f docker-compose-test.yml build
- docker-compose -f docker-compose-test.yml run test
addons:
  ssh_known_hosts: $DEPLOY_HOST
before_install:
- bash _scripts/install.sh
after_success:
- bash _scripts/deploy.sh
env:
  global:
  - secure: XKe0EKjsOiJeVlsbIMV4oB55N61GaTzf4ffj+08E8bGqMFhsqCPVC5ZFifgnanS6Z1FfN/TvA93JTJG0Qsu6M9ozZjDlLQrP9/N687XnEnOVaWrNpY/PRGNgPtWM9zbYvNMQSpFRIi16pYPxspcS/HIjtK9JVOimklLRYCErDF/jT1VL3xY5olqOvxM68oDeMJDTjyfAGZDVDwpsXFVmwn/3eCdrTzewG7WWtw31ZakuSw+qia1WDsqKJji+wx3HBzuBqIwgGIB8Or+gZUtUZHdDZMscsbiuzX3Mn4f0JD8t3KjhWO1ysY9Y52xwye7ZUoaidM94R/9z33vFsTKzn0EDB1cb+8O4Wk98vxbqkG3A8UgvysXXDHAxISWRNbcApNOmxlRN3NqeNksYtSomR9PQ1Xu1jjgqXOqUjzmUHAEvCNFj3ZfKzTfbfwedJdL5fVVUJvQ8tjrKEhxOfSRk+OQ8GTn4uSLrmc1Y6DduyuuyPcUHdvbs9O3cP8gd29yVZgUW/lG+qsv3qWZ6xGNlpvwPAQvkuzHX+pCzsefkXU46km8Ptslql6lV9RSG8ZBwUOKxhuKG9+Rk45GrQX3iHPNj1PRyKo3MLQPxjCr8KH8mSBZpd9aG6gScD2jpbeJySIJKKc7qTIrGSAW2Va4Qn3N139003WlscuPDf66p7J4=
  - secure: HRIF5uAeeWUZOQyYo1jtgdwS3tEe3BiRQvbpEQoWzXmIVbc6RiejSD+VYqOggg37dRMFJXMX1pSs9aLEyCzTzZhDJyg7Bnd7D58pJD1JisNPe7thPrfFTL4ztbqCotHDXO9R2iKIMUtip6DDugjiUBw8NfKIfLvEHppJ3/lvCeZ1EKojp58e3Gx2JYyJxV48DuHR/x/XpE7xlYgShAx+byfIv3MnezBs0F0FIg0CMVW3cjrvZntyuJ7uwukmtq4FHrbpryJIILt5dmt115qnoKVhe7MgzreQ+UD0ZCDrymBTjwBEbPqV2uJr7LGGPmSlN/lM+eWS+MJs+JY0ov4NwLp79uZVtAsbtWIZGOOo9lPr32qeYcJHaA134MRiDKKKtkpFCSIK9IKZwvhAClmYWmTV/W/Q3Fb5JoObU59pO4Mvr7pjCJUCB+BvqrP44jcEVIHS/KJyDUcWU7saVrpnR82kwoFULY3ixeASFr4W5iA4VNcjfJFnUqmy4g9Hwx4/4q4Rz2IRSkxhwlrYsSplM0wVKL2pMHG1rbYgdxZlHvDnreQQ07MNJiwXXzegG8d1uQH6XLV7jaAE07XvosoIIVsNrRhiRgj6asdOiEEY0ulmYrv6F3Mov0mUf5EOt2p3G977l6whwI3pXgyJU5mdVZWaya1lOD7ZCi64RmbRwxk=
  - secure: fRblkizk2oe/1fZcb7to6djCL70Ph5E8fk4Vroo6e5nJgbsmex2BDv0WrgbPcw2Oiro+Qe35H/eJHOHyvYTLy1413tGG/cR1G28NIdPBRa3+aZgbY0T6+uWBpY1j1eljZqA2hxfNxM0kSZ06smtOKnevas68a1Y4V2lJ1XFdGLn/umq8KwVUkBd/09PjtIqagvH6fMeaNc2TZGZC3e9L+EIcUKKwKEvZwGBVelslPJh26F1TU5Je3tAE2iZo9siwJpgRC7PolEoPq0jTrjAwfguF492oEO99beCbU+epw0Eb0w1i/8rwAdac1yrHR91ZCmybP3i8VIfVjwe7CXMrt08JF18PpIWVqw7usyfGzyyFs5G8LU/HAEPdXYucJSytf9lKE/xsMI6Wd/C2IYN03XQwWk6OP8fFXjnE2sU9G/tQ3a/MIIstD/U2wgBpdiMO7nQlLiYpXlFJhGvNaPiQdi2PMmh2kz6ukng9M5mP6IiC0tSuNEAsG2gZ4OpzHlJ2X/GcrUPvhg0WcM6UGAGv0EfpAW0sT/byFnZAebagclEk0Ypoe87nMxKDesKsddPhxebK+w82O3mxJ0k9F0crRtWg3J3GpJSmODo1hgt3sRmR2ght1y5ANicIswNTn878PQXk17BPdhULH9F/RYESVfWkEHNOqVzEybpfXz8jw9U=
