base:
  build: .
  ports:
    - "8000:8000"
  container_name: api-gateway
  environment:
    NODE_PATH: app/src
    PORT: 8000
mongo:
  image: mongo
  container_name: api-gateway-mongo
  command: --smallfiles
  ports:
    - "27017"
  volumes:
    # in osx the host machine volume directory cannot be under /Users
    # http://stackoverflow.hex1.ru/questions/34390220/how-to-mount-external-volume-for-mongodb-using-docker-compose-and-docker-machine
    - /var/docker/data/mongodb:/data/db
  restart: always
redis:
  image: redis
  container_name: api-gateway-redis
  command: redis-server --appendonly yes
  ports:
    - "6379:6379"
  volumes:
    # in osx the host machine volume directory cannot be under /Users
    # http://stackoverflow.hex1.ru/questions/34390220/how-to-mount-external-volume-for-mongodb-using-docker-compose-and-docker-machine
    - /var/docker/data/redisdb:/data
  restart: always
