web:
  extends:
    file: base.yml
    service: base
  command: start
  environment:
    NODE_ENV: staging
  links:
    - mongo

mongo:
  extends:
    file: base.yml
    service: mongo
redis:
  extends:
    file: base.yml
    service: redis
