develop:
  extends:
    file: base.yml
    service: base
  ports:
    - "35729:35729"
  container_name: api-gateway-develop
  # environment:
  #   NODE_ENV: dev
  command: bash -c 'npm install; npm run develop'
  links:
    - mongo
start-dev:
  extends:
    file: base.yml
    service: base
  container_name: api-gateway-start-dev
  command: bash -c 'npm install; npm run startDev'
  links:
    - mongo
test:
  extends:
    file: base.yml
    service: base
  container_name: api-gateway-test
  command: bash -c 'npm install; npm test'

web:
  extends:
    file: base.yml
    service: base
  command: bash -c 'npm install; npm start'
  links:
    - mongo

mongo:
  image: mongo
  container_name: api-gateway-mongo
  command: --smallfiles
  ports:
    - "27017:27017"
  volumes:
    # in osx the host machine volume directory cannot be under /Users
    # http://stackoverflow.hex1.ru/questions/34390220/how-to-mount-external-volume-for-mongodb-using-docker-compose-and-docker-machine
    - /var/docker/data/mongodb:/data/db
  restart: always
