web:
  extends:
    file: base.yml
    service: base
  command: start
  ports:
    - "80:8000"
  env_file:
    - prod.env
  links:
    - mongo
    - redis
mongo:
  extends:
    file: base.yml
    service: mongo
redis:
  extends:
    file: base.yml
    service: redis
